import Image from "next/image";
import localFont from 'next/font/local'
import "./globals.css";

import brandLogo from "../../public/ares.svg";
import iconLang from "../../public/language.svg";
import iconDropdown from "../../public/dropdown.svg";
const Gilmer = localFont({
  src: [
    {
      path: '../../public/Gilmer-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/Gilmer-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/Gilmer-Regular.woff2',
      weight: '400',
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-geist-sans',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Gilmer.variable} font-sans antialiased`}>
        <header className="flex items-center justify-between absolute top-8 left-1/2 -translate-x-1/2 bg-white/10 backdrop-blur-xs w-full max-w-[1150px] h-[70px] rounded-4xl overflow-hidden px-7 font-bold">
          <Image src={brandLogo} alt="Ares" />
          <nav className="flex items-center space-x-6">
            <a href="">
              <span>Proyectos</span>
              <Image src={iconDropdown} alt="Dropdown Icon" />
            </a>
            <a href="">El estudio</a>
            <a href="">
              <span>Cultura Ares</span>
              <Image src={iconDropdown} alt="Dropdown Icon" />
            </a>
            <a href="">Blog</a>
          </nav>
          <nav className="flex items-center space-x-6">
            <a href="" className="flex items-center">
              <Image src={iconLang} alt="Language Icon" />
              <span className="block ml-2">ES</span>
              <Image src={iconDropdown} alt="Dropdown Icon" />
            </a>
            <a href="" className="bg-white text-black px-6 py-3 rounded-full">Hablemos</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
